# Visualization

## Preprocessing

In [1]:
# Packages
import pandas as pd
import numpy as np
import os
import altair as alt # pip install altair
from altair_saver import save # pip install altair_saver
from pyecharts import options as opts     # pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyecharts
from pyecharts.charts import  Timeline,Map

# set output path
os.chdir("/Users/zhuziyue/Desktop/MDA_project")

# importing data from S3
project_dir = ("https://projectmda.s3.us-east-2.amazonaws.com/data/Data+Viz/")

In [2]:
# Data import
df = pd.DataFrame(pd.read_csv(project_dir + "Predict_Heatwaves.csv")) 
month = pd.DataFrame(pd.read_excel(project_dir + "HeatWaves.xlsx")) # original sheet 2000-2020

In [3]:
# Data processing  
df['Unnamed: 0']=0
df = df.drop(['heatwave'],axis=1)
df= df.drop_duplicates() 
df.index = df['Dis No']
df['tavg_F'] = df.tavg_F.round(2)
df['HI'] = df.HI.round(2)
df['Rel_Hum'] = df.Rel_Hum.round(2)

In [4]:
df

,Unnamed: 0,Dis No,Country,Year,Month,Rel_Hum,tavg,tmin,tmax,prcp,wspd,Region,tavg_F,HI
Dis No,,,,,,,,,,,,,,
2020-0530-GBR,0,2020-0530-GBR,United Kingdom of Great Britain and Northern I...,2000,1,72.0,6.093333,-3.50,12.00,34.763333,21.513333,Northern Europe,42.97,118.11
2020-0530-GBR,0,2020-0530-GBR,United Kingdom of Great Britain and Northern I...,2000,2,77.0,6.863333,-1.94,12.42,61.026667,27.000000,Northern Europe,44.35,110.67
2020-0530-GBR,0,2020-0530-GBR,United Kingdom of Great Britain and Northern I...,2000,3,75.0,7.378333,-2.24,15.10,20.363333,18.753333,Northern Europe,45.28,108.72
2020-0530-GBR,0,2020-0530-GBR,United Kingdom of Great Britain and Northern I...,2000,4,81.0,7.613333,-1.04,17.44,47.930000,17.596667,Northern Europe,45.70,103.25
2020-0530-GBR,0,2020-0530-GBR,United Kingdom of Great Britain and Northern I...,2000,5,82.0,11.556667,3.70,22.84,34.390000,16.136667,Northern Europe,52.80,83.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002-0354-NGA,0,2002-0354-NGA,Nigeria,2020,8,82.0,27.420000,20.40,39.90,321.440000,9.800000,Western Africa,81.36,87.69
2002-0354-NGA,0,2002-0354-NGA,Nigeria,2020,9,83.0,28.760000,20.70,41.60,38.440000,8.400000,Western Africa,83.77,94.46
2002-0354-NGA,0,2002-0354-NGA,Nigeria,2020,10,65.0,30.140000,15.90,41.70,9.200000,8.700000,Western Africa,86.25,93.54
2002-0354-NGA,0,2002-0354-NGA,Nigeria,2020,11,39.0,26.560000,11.70,37.60,0.000000,11.800000,Western Africa,79.81,79.72
2002-0354-NGA,0,2002-0354-NGA,Nigeria,2020,12,36.0,24.880000,11.00,39.00,0.000000,9.400000,Western Africa,76.78,77.94

In [ ]:
df['Date_current']= df['Dis No']
#df['Date_current_time']= df['Dis No']
df['Heatwave_Year']= df['Dis No']

for i in range(len(df)):
    year = df['Year'][i]
    month = df['Month'][i]
    df['Date_current'][i] = str(year) + '-' + str(month)
#for i in range(len(df)):
#    df['Date_current_time'][i] = pd.to_datetime(df['Date_current'][i], format='%Y-%m')
for i in range(len(df)):
    df['Heatwave_Year'][i] = df['Dis No'][i][0:4]

<ipython-input-5-982330f01e65>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date_current'][i] = str(year) + '-' + str(month)
<ipython-input-5-982330f01e65>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Heatwave_Year'][i] = df['Dis No'][i][0:4]

In [ ]:
month = pd.DataFrame(pd.read_excel(project_dir + "HeatWaves.xlsx")) # original sheet 2000-2020

In [ ]:
month = month[['DisNo','EndMonth','TotalDeaths']] #  Some countries heatwave last for more than 1 month, End month shall prevail
month.columns = ['Dis No','Heatwave_Month','TotalDeaths']
df = df.drop(['Dis No'],axis=1)
df_base = df.merge(month,on='Dis No',how='left')
df_base = df_base.drop_duplicates()

### Data for (Line + Bar) chart 1

In [ ]:
df_chart1 = df_base # 147 Disaster number * 12months * 21years

### Data for (Bar) chart 2

In [ ]:
df_chart2 = df_base.loc[df_base['Month']==df_base['Heatwave_Month']]
df_chart2 = df_chart2.loc[df_chart2['Year']==df_chart2['Heatwave_Year'].astype(int)]
df_chart2 = df_chart2.drop_duplicates()  # 147 Disaster number

### Data for (MAP) chart 3

In [ ]:
df_chart3 = df_base.loc[df_base['Month']==df_base['Heatwave_Month']]
df_chart3 = pd.DataFrame(df_chart3) 
df_chart3 = df_chart3.drop_duplicates(['Country','Year'])
countryname= df_chart3['Country']
df_chart3['Countrynew'] = df_chart3['Country']
df_chart3.loc[df_chart3['Country'] == 'United States of America (the)','Countrynew']= 'United States'
df_chart3.loc[df_chart3['Country'] == 'Netherlands (the)','Countrynew']= 'Netherlands'
df_chart3.loc[df_chart3['Country'] == 'Macedonia (the former Yugoslav Republic of)','Countrynew']= 'Macedonia'
df_chart3.loc[df_chart3['Country'] == 'Czech Republic (the)','Countrynew']= 'Czech Rep.'
df_chart3.loc[df_chart3['Country'] == 'Korea (the Republic of)','Countrynew']= 'Korea'
df_chart3.loc[df_chart3['Country'] == 'Sudan (the)','Countrynew']= 'Sudan'
df_chart3.loc[df_chart3['Country'] == "Korea (the Democratic People's Republic of)",'Countrynew']= 'Dem. Rep. Korea '
df_chart3.loc[df_chart3['Country'] == 'Bolivia (Plurinational State of)','Countrynew']= 'Bolivia'
df_chart3.loc[df_chart3['Country'] == 'Russian Federation (the)','Countrynew']= 'Russia'
df_chart3.loc[df_chart3['Country'] == 'United Kingdom of Great Britain and Northern Ireland (the)','Countrynew']= 'United Kingdom'
df_chart3.loc[df_chart3['Country'] == 'Bosnia and Herzegovina','Countrynew']= 'Bosnia and Herz.'
df_chart3 # 49 countries, 49*21 data

### Data for (Line) chart 4

In [ ]:
def function(m, n, e, f):
    if (m == n) & (e == f):
        return 1
    else:
        return 0

df_base['signal']= df_base.apply(lambda x : function(x['Year'],x['Heatwave_Year'],x['Month'],x['Heatwave_Month']),axis = 1)
df_chart4 = df_base.drop_duplicates()
df_chart4 # 147 Disaster number * 12months * 21years

In [ ]:
dis_number = ["2000-0382-BGR","2000-0398-CYP","2000-0379-GRC","2000-0324-HRV","2000-0473-ISR","2000-0471-JOR","2000-0487-MAR","2000-0351-PAK",
"2000-0380-ROU","2000-0381-TUR","2000-0383-SCG","2000-0433-USA","2002-0531-CHN","2001-0779-NZL","2001-0404-RUS","2002-0290-IND",
"2002-0354-NGA","2002-0284-PAK","2001-0770-USA","2002-0355-USA","2003-0391-AUT","2003-0391-BEL","2003-0391-CHE","2003-0391-DEU","2003-0391-ESP","2003-0391-FRA","2003-0391-HRV",
"2003-0250-BGD","2003-0391-CZE","2003-0785-DZA","2003-0391-GBR","2004-0333-ALB","2004-0310-CHN","2004-0361-ESP","2003-0391-SVN","2003-0250-IND","2003-0391-ITA","2003-0391-SVK","2003-0391-LUX","2003-0391-NLD","2003-0250-PAK","2003-0391-PRT","2004-0352-JPN","2004-0333-MKD","2004-0333-ROU","2004-0361-SPI","2005-0323-BGD","2005-0339-CHN","2005-0323-IND",
"2006-0383-BEL","2006-0383-DEU","2006-0383-ESP","2006-0383-FRA","2006-0237-IND","2005-0347-PAK","2005-0820-PRT","2005-0756-ROU",
"2005-0687-USA","2006-0383-NLD","2006-0254-PAK","2006-0383-PRT","2006-0348-ROU","2006-0387-USA","2006-0427-USA","2007-0235-BGR","2007-0235-ALB","2007-0235-AUT","2007-0235-BIH","2007-0235-GRC","2007-0235-ITA","2007-0235-MKD",
"2007-0235-CYP","2007-0235-HUN","2007-0207-IND","2007-0358-JPN","2008-0662-JPN","2009-0175-IND","2007-0235-ROU","2007-0235-TUR","2007-0235-SRB","2007-0235-SVK","2009-0616-AUS","2010-0057-BRA",
"2009-0658-JPN","2010-0206-IND","2010-0331-JPN","2010-0372-RUS","2011-0329-ITA","2011-0264-USA","2011-0573-JPN","2013-0365-BOL","2013-0582-CHN","2013-0549-GBR","2013-0208-IND","2013-0316-JPN","2014-0010-AUS","2012-0214-USA",
"2014-0546-PAK","2015-0410-BEL","2014-0578-JPN","2015-0342-EGY","2015-0410-FRA","2015-0189-IND","2015-0575-JPN","2015-0610-JPN","2015-0611-JPN","2015-0232-PAK","2016-0133-IND",
"2015-0393-SDN","2016-0036-ZAF","2018-0235-BEL","2018-0195-CAN","2018-0235-DEU","2018-0235-ESP","2019-0366-AUT","2019-0296-BEL","2019-0366-BEL","2019-0296-DEU",
"2019-0366-DEU","2019-0296-ESP","2016-0538-JPN","2017-0144-IND","2018-0256-PRK","2018-0235-FRA","2018-0235-GBR","2018-0235-ITA",
"2018-0226-JPN","2018-0226-KOR","2018-0235-NLD","2018-0143-PAK","2018-0235-PRT","2019-0296-FRA","2019-0366-FRA","2019-0296-GBR","2019-0217-IND","2019-0223-IND","2019-0296-ITA","2019-0463-JPN","2019-0467-JPN","2019-0366-NLD","2019-0650-BEL","2019-0650-GBR","2020-0530-BEL","2020-0530-FRA","2020-0530-GBR","2020-0530-NLD"]
year = ["2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020"]
country_name = ['Albania'	,'Algeria'	,'Australia'	,'Austria'	,'Bangladesh'	,'Belgium'	,'Bosnia and Herzegovina'	,'Bolivia (Plurinational State of)'	,'Bulgaria'	,'Brazil'	,'Canada'	,
                'Canary Is'	,'China'	,'Croatia'	,'Cyprus'	,'Czech Republic (the)'	,'Egypt'	,'France'	,'Germany'	,'Greece'	,'Hungary'	,'India'	, 'Israel'	,'Italy'	,'Japan'	,
                'Jordan'	,"Korea (the Democratic People's Republic of)"	,'Korea (the Republic of)'	,'Luxembourg'	,'Macedonia (the former Yugoslav Republic of)'	,'Morocco'	,
                'Netherlands (the)'	,'New Zealand'	,'Nigeria'	,'Pakistan'	,'Portugal'		,'Romania'	,'Russian Federation (the)'	,'Serbia'	,'Serbia Montenegro'	,'Slovakia'	,'Slovenia'	,
                'South Africa'	,'Spain'	,'Sudan (the)'	,'Switzerland'	,'Turkey'	,'United Kingdom of Great Britain and Northern Ireland (the)'	,'United States of America (the)'	]

## Chart 1

In [ ]:
# Chart1
slider = alt.binding_range(min=2000, max=2020, step=1)
selector = alt.selection_single(name="Year", fields=['Year'],
                                bind=slider)
bar = alt.Chart(df_chart1).mark_bar().encode(
    x='Month:N',
    y='Rel_Hum:Q'
)

line =  alt.Chart(df_chart1).mark_line(color='red',size = 0.5).encode(
    y='tavg:Q',
    x='Month:N'
)

c = bar + line

c = c.add_selection(
    selector
).transform_filter(
    selector
)

In [ ]:
# filter countries

DisNo_filter = alt.binding_select(options=dis_number)
DisNo_select = alt.selection_single(fields=['Dis No'], bind=DisNo_filter, name="dis number")

chart1 = c.add_selection(
    DisNo_select
).transform_filter(
    DisNo_select
)
alt.data_transformers.disable_max_rows()
chart1
save(chart1, "chart1(line&bar).html")

## Chart 2

In [ ]:
# Chart2
chart2 = alt.Chart(df_chart2).mark_bar(size = 10).encode(
    y=alt.Y('Year:N'),
    x='sum(TotalDeaths)',
    color=alt.Color('Country',legend=None),
    tooltip = ['Country','TotalDeaths','Dis No']
).interactive()

chart2 
save(chart2, "chart2(stack_bar).html")

## Chart 3

In [ ]:
# Chart3
chart3 = Timeline()
for i in range(2000, 2021):
        df_all_layer = df_chart3.loc[df_chart3['Year']==i]
        map0 = (
        Map()
        .add("HI", [list(z) for z in zip(df_all_layer['Countrynew'], df_all_layer['HI'])], "world",is_map_symbol_show=False)
        .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
        .set_global_opts(
            title_opts=opts.TitleOpts(title="Map-{}".format(i)),
            visualmap_opts=opts.VisualMapOpts(max_=150,min_=50),
        )
    )
        chart3.add(map0, "{}Year".format(i))
chart3.render("chart3(map).html")

## Chart 4

In [ ]:
# Chart4
# change date as time variable
alt.data_transformers.disable_max_rows()
scales = alt.selection_interval(bind='scales')
nearest = alt.selection(type='single', nearest=True, on='mouseover',fields=['Dis No'])


line = alt.Chart(df_chart4).mark_line().encode(
    alt.X('Date_current:T'),
    alt.Y('HI:Q'),
    alt.Color('Dis No:N'),
    #tooltip = ["Country","Year","Month_x","Year_HW","Month_y","signal","HI","Dis No"]
).add_selection(
    scales
)

rule = alt.Chart(df_chart4).mark_rule().encode(
    y='mean(HI)',
    color=alt.value('red'),
    size=alt.value(0.5)
)

point = alt.Chart(df_chart4).mark_point().encode(
    x = 'Date_current:T',
    y = 'HI:Q',
    size=alt.value(1),
    color=alt.value('red'),
).transform_filter(alt.datum.single == 1)

selectors = alt.Chart(df_chart4).mark_point().encode(
    x='Date_current:T',
    y='HI:Q',
    tooltip = ["Dis No","Country","Year","Month","signal","HI"],
    opacity=alt.value(0),
).add_selection(
    nearest
)

chart = line + rule + point + selectors
# filter countries
country_filter = alt.binding_select(options=country_name)
country_select = alt.selection_single(fields=['Country'], bind=country_filter, name="country")

chart4 = chart.add_selection(
    country_select
).transform_filter(
    country_select
)

save(chart4, "chart4(line).html")